package sample.data.jpa.domain;

import java.sql.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table
public class Appointment {

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private long id;

	@NotNull
	@Column
	private Date date;

	@NotNull
	@Column
	private int duration;

	@NotNull
	@Column
	private User user;

	@NotNull
	@Column
	private Worker worker;

	@Column
	private String description;

	public Appointment() {
	}

	public Appointment(long id) {
		this.id = id;
	}

	public Appointment(Date date, int duration, User user, Worker worker) {
		this(date, duration, user, worker, "");
	}

	public Appointment(Date date, int duration, User user, Worker worker, String description) {
		this.date = date;
		this.duration = duration;
		this.user = user;
		this.worker = worker;
		this.description = description;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getDuration() {
		return duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	@ManyToOne(targetEntity = User.class, fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(targetEntity = Worker.class, fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn
	public Worker getWorker() {
		return worker;
	}

	public void setWorker(Worker worker) {
		this.worker = worker;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Override
	public String toString() {
		return "Appointment [id=" + id + ", date=" + date + ", duration=" + duration + ", user=" + user.getId()
				+ ", worker=" + worker.getId() + ", description=" + description + "]";
	}

}
